export interface LedgerCellOverride {
  cellId: string;
  originalValue: number;
  overriddenValue: number;
  overriddenBy: string;
  reason: string;
  timestamp: string;
}

export interface ExcelRowItem {
  rowNum: number;
  code: string;
  categoryName: string;
  cashAmount: number;
  cardAmount: number;
  upiAmount: number;
  totalAmount: number;
  isAutoGenerated: boolean;
  isFormula: boolean;
}

export interface DailyMasterLedger {
  id: string;
  date: string;
  centreId: string;
  centreName: string;
  openingCash: number;
  // Auto-Aggregated Category Breakdowns
  cashSales: number;
  cardSales: number;
  upiSales: number;

  membershipCash: number;
  membershipCard: number;
  membershipOnline: number;

  giftCardSales: number;
  expenses: number;
  staffAdvances: number;
  salaryPayments: number;
  vaultHandover: number;
  refunds: number;

  // Formula Totals
  totalGrossRevenue: number;
  totalCashIn: number;
  totalCashOut: number;

  expectedCash: number;
  actualCash: number;
  difference: number;
  differenceReason?: string;

  isFinalised: boolean;
  finalisedBy?: string;
  finalisedAt?: string;

  overrides: Record<string, LedgerCellOverride>;
}

// LEVEL 2: Monthly Financial Register Row
export interface MonthlyRegisterRow {
  date: string;
  openingCash: number;
  cashSales: number;
  cardSales: number;
  upiSales: number;
  membershipCash: number;
  membershipCard: number;
  membershipOnline: number;
  giftCardSales: number;
  expenses: number;
  staffAdvances: number;
  salaryPayments: number;
  vaultHandover: number;
  refunds: number;
  expectedClosingCash: number;
  actualClosingCash: number;
  difference: number;
  remarks: string;
  isFinalised: boolean;
}

// LEVEL 3: Yearly Register Row
export interface YearlyRegisterRow {
  month: string; // e.g. "Jan 2026", "2026-01"
  monthName: string;
  revenue: number;
  expenses: number;
  profit: number;
  membershipSales: number;
  giftCardSales: number;
  bookingsCount: number;
  avgTicketSize: number;
  cashDifferences: number;
}

// MONTHLY BOOKING REGISTER ROW
export interface MonthlyBookingRegisterRow {
  date: string;
  totalBookings: number;
  walkIns: number;
  onlineBookings: number;
  completed: number;
  cancelled: number;
  noShows: number;
  revenue: number;
  occupancyPercentage: number;
}
